import React from 'react';
import { Helmet } from 'react-helmet';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Calendar, Utensils, Download } from 'lucide-react';
import { motion } from 'framer-motion';

const MealCard = ({ day, meals, delay }) => (
    <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay }}
    >
        <Card className="glassmorphism rounded-2xl h-full">
            <CardContent className="p-6">
                <h3 className="font-bold text-xl mb-4 text-primary">{day}</h3>
                <ul className="space-y-2 text-muted-foreground">
                    {meals.map((meal, index) => (
                        <li key={index} className="flex items-start gap-2">
                           <Utensils className="h-4 w-4 mt-1 text-primary/70 shrink-0" />
                           <span><span className="font-semibold text-foreground">{meal.time}:</span> {meal.dish}</span>
                        </li>
                    ))}
                </ul>
            </CardContent>
        </Card>
    </motion.div>
);

const MealPlannerPage = () => {
  const weeklyPlan = [
      { day: 'Monday', meals: [{time: 'Breakfast', dish: 'Oats with berries'}, {time: 'Lunch', dish: 'Quinoa Salad'}, {time: 'Dinner', dish: 'Lentil Soup'}] },
      { day: 'Tuesday', meals: [{time: 'Breakfast', dish: 'Scrambled Tofu'}, {time: 'Lunch', dish: 'Leftover Lentil Soup'}, {time: 'Dinner', dish: 'Veggie Stir-fry'}] },
      { day: 'Wednesday', meals: [{time: 'Breakfast', dish: 'Smoothie'}, {time: 'Lunch', dish: 'Chickpea Sandwich'}, {time: 'Dinner', dish: 'Pasta with Veggies'}] },
  ];
    
  return (
    <>
      <Helmet>
        <title>AI Meal Planner - SwasthAI</title>
        <meta name="description" content="Get a personalized weekly meal plan generated by AI, based on your dietary restrictions and health goals." />
      </Helmet>
      <div className="main-container">
        <div className="text-center">
            <h1 className="page-title">AI-Powered Meal Planner</h1>
            <p className="page-description">Your weekly menu, sorted. Our AI creates balanced and delicious meal plans tailored just for you. More features are coming soon!</p>
        </div>

        <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="flex justify-center gap-4 mb-8"
        >
            <Button size="lg"><Calendar className="mr-2 h-5 w-5" /> Generate This Week's Plan</Button>
            <Button size="lg" variant="outline"><Download className="mr-2 h-5 w-5" /> Download Grocery List</Button>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {weeklyPlan.map((dayPlan, index) => (
                <MealCard key={dayPlan.day} day={dayPlan.day} meals={dayPlan.meals} delay={index * 0.1} />
            ))}
        </div>
      </div>
    </>
  );
};

export default MealPlannerPage;